name: "CI Project Action"
description: "Composite action to build and test a workspace project (uses project_path input)"

inputs:
  project_path:
    description: 'Path to the project e.g. packages/auth or services/api-gateway'
    required: true
  node-version:
    description: 'Node version to install (defaults to 18)'
    required: false
    default: '18'

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Cache npm and node_modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.npm/_cacache
          node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies (root)
      run: npm ci
      shell: bash

    - name: Build (workspace preferred, fallback)
      run: |
        npm --workspace=${{ inputs.project_path }} run build --if-present || (cd ${{ inputs.project_path }} && npm ci && npm run build --if-present)
      shell: bash

    - name: Test (workspace preferred, fallback)
      run: |
        npm --workspace=${{ inputs.project_path }} run test --if-present || (cd ${{ inputs.project_path }} && npm ci && npm run test --if-present)
      shell: bash
